config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login' }
  root to: 'products#index'
  resources :products
  resources :categories

  resources :orders do
  
    collection do
      get :open
    end

    collection do
      get :payment
    end

    member do
      put :ready
    end

    member do
      put :complete
      resources :charges
    end

    member do
      put :cancel
    end

  end
  

  
  get  '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/views/shared/_footer.html.erb
<footer class="pt-2 my-md-5 pt-md-5 border-top">
<div class="row">
<div class="col-md-4">
</div>
<div class="col-md-4">
  <p class="float-right">
    <%= link_to 'Locus Ubi Vendere - 2018', user_session_path, class:'badge badge-pill badge-light' %>
  </p>
</div>
<div class="col-md-4">
</div>
</div>
</footer>

app/views/shared/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <nav class="my-0 mr-md-auto">
      <%= link_to 'Order', root_path, class: "p-2" %>
      <%= link_to 'Categories', categories_path, class: "p-2" if logged_in?(:site_admin) %>
      <%= link_to ('Open orders'), open_orders_path, class: "p-2" if logged_in?(:user, :site_admin) %>
      <%= link_to 'Ready orders', payment_orders_path, class: "p-2" if logged_in?(:user, :site_admin) %>
  </nav>
  <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-danger" if logged_in?(:user, :site_admin) %>
      <%= link_to (fa_icon "shopping-cart 2x"), cart_path, class:"p-2" %>
  </nav>
      <h5><%= link_to current_cart.items_count, cart_path, class: "badge badge-pill badge-primary" %></h5>
</div>