config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login' }
  root to: 'products#index'
  resources :products
  resources :categories

  resources :orders do
  
    collection do
      get :open
    end

    collection do
      get :payment
    end

    member do
      put :ready
    end

    member do
      put :complete
      resources :charges
    end

    member do
      put :cancel
    end

  end
  

  
  get  '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :items, class_name: 'OrderItem'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  access all: {except: [:open, :payment, :ready, :complete]}, user: :all, site_admin: :all

  def new
    @order = current_cart.order
  end

  def show
    @order = Order.find_by_id(params[:id])
    redirect_to payment_orders_path unless @order.status == "payment"
  end

  def create
    @order = current_cart.order
    respond_to do |format|
      if @order.total > 0
        session[:cart_token] = nil
        @order.update_attributes(order_params.merge(status: :open))
        format.html { redirect_to root_path, notice: 'Order successfully submitted' } 
      else
        format.html { redirect_to root_path, notice: 'Cannot submit empty orders' }
      end
    end
  end

  def open
    @orders = Order.where(status: :open)
    render action: :index
  end

  def ready
    @order = Order.find_by_id(params[:id])
    @order.update_attributes(status: :payment)
    redirect_to open_orders_path
  end

  def complete
    @order = Order.find_by_id(params[:id])
    @order.update_attributes(status: :complete)
    redirect_to payment_orders_path
  end

  def cancel
    @order = Order.find_by_id(params[:id])
    @order.update_attributes(status: :cancelled)
    respond_to do |format|
      format.html { redirect_to open_orders_path, notice:'Order cancelled'}
    end
  end

  def payment
    @orders = Order.where(status: :payment)
    render action: :payment
  end


  private

  def order_params
    params.require(:order).permit(:table)
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>


  <h1>Open Orders</h1>
    <div class="card-deck mb-3">  <% @orders.each do |order| %>
        <div class="col-xs-12 col-md-6 col-lg-4">
          <div class="card mb-4 bg-<%= order_time ((Time.now - order.updated_at)/60).to_int %>"  style="width: 22rem;">
            <div class="card-header navbar text-white">
              <div class="float-left">
                <h6>
                  Order #<%= order.id %> 
                </h6>
              </div>
              <div class="float-center">
                <h6>Table <%= order.table %></h6>
              </div>
              <div class="float-right">
                <%= link_to (fa_icon "times-circle"), cancel_order_path(order), data: { confirm: "Are you sure you want to CANCEL the order?" } ,method: :put, class:'text-white' %>
              </div>
            </div>
                <% order.items.each do |item| %>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                 [<%= item.quantity %>] <%= item.product.title %> 
                </li>          
              </ul>
                <% end %>
              <%=link_to 'Order Up!', ready_order_path(order), class: (order_time_button ((Time.now - order.updated_at)/60).to_int), method: :put  %>
              <footer class="blockquote-footer text-white">
                Submitted <%= distance_of_time_in_words(order.updated_at, Time.now) %> ago  
              </footer>
          </div>
        </div>
      <% end %>
      <br>
  </div>

<script>
setInterval(function(){
  Turbolinks.visit() 
    }, 5000)
</script>

app/views/orders/new.html.erb
<p id="notice"><%= notice %></p>
<h2>Checkout</h2>


  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_for @order, url: checkout_path do |f| %>
    <div class="form-group"> 
      <%= f.label :table %>
      <%= f.text_field :table, class: "form-control" %>
      <%= f.submit 'Submit Order', class: "btn btn-success" %>
    <% end %>
    <h5>For take-out, leave table empty.</h5>
    </div>
  </div>
  <div class="col-md-4"></div>

app/views/orders/payment.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Ready for payment</h1>

  <ul>
    <% @orders.each do |order| %>
    <li>
      <%= order.id %> Table(<%= order.table %>) - <%= number_to_currency order.total %>
      <%= link_to 'Submit Payment', order, class: "btn btn-outline-primary btn-sm" %> <%= link_to (fa_icon "credit-card"), order %>
    </li>
    <% end %>
  </ul>
</div>

app/views/orders/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h1>Payment Screen</h1>
<h2>Order <%= @order.id %> Table <%= @order.table %></h2>
<h2>Subtotal <%= number_to_currency @order.sub_total %></h2>
<h2>Tax <%= number_to_currency @order.tax %></h2>
<h2>Amount due <%= number_to_currency @order.total %></h2>

<%= form_tag charges_path(@order) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>
  

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Restaurant purchase"
          data-amount=parseInt(<%= @order.total*100 %>);
          data-locale="auto"></script>
<% end %>
  
  <br>
  <br>
  
  <%= link_to 'Click here upon successful cash or check payment', complete_order_path(@order), class:'btn btn-outline-success', method: :put %>
</div>