config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login' }
  root to: 'products#index'
  resources :products
  resources :categories

  resources :orders do
  
    collection do
      get :open
    end

    collection do
      get :payment
    end

    member do
      put :ready
    end

    member do
      put :complete
      resources :charges
    end

    member do
      put :cancel
    end

  end
  

  
  get  '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :title) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="table-responsive-md">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.title, product %></td>
          <td><%= product.description %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= product.category.title %></td>
          <td>
            <%= form_tag order_items_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= number_field_tag :quantity, 1, in: 1..20, class:"form-control input-lg col-6" %>
              <%= submit_tag "Add to Order", class: "btn btn-success" %>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-warning" if logged_in?(:site_admin) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Proceed to checkout", cart_path, class:"btn btn-primary"  %>
</div>

<br>

<%= link_to 'New Product', new_product_path, class: "btn btn-primary" if logged_in?(:site_admin) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @product.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency @product.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @product.category.title %>
  </p>

<%= link_to 'Edit', edit_product_path(@product) if logged_in?(:site_admin) %> 
<%= link_to 'Back', products_path %>
</div>